language: node_js
node_js:
- node
install:
- npm install
script:
- mkdir -p build
- npm run build-gzip
- ls build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: dawidvdh.com
  acl: public_read
  skip_cleanup: true
  local_dir: build
  region: us-east-1
  detect_encoding: true
branches:
  only:
  - master
  - /^greenkeeper/.*$/
