language: node_js
node_js:
- node
script:
- mkdir -p build
- cp index.html build/
- ls build
deploy:
  provider: s3
  access_key_id: AKIAJ6D6QZ6KEWJFFZOQ
  secret_access_key:
    secure: czi0gEIsIle3dwHhBnMLtCpeCK11p7FoaunFQqvQ/lVXFMeCkHgFmk6bBmrlRM/0+GBxOgZ0raRh36Z2IJTT3pb8/LF8ZdQnukSaRd+BV5gq+sdgy/GRfUPfXGahi3MZ7Qvyoe84otGqoq/YUTfdMg6cDAomfHeR5bZJpLUN8UMMZmx2PBXWYZqurEy7jhg78Cao6R4nCGEBn4heaH3CBUP4/r/zuFHi/jlkoFvODWnK2CwhP7ceXtz64h5Xug02RrM5Y/qUv9YqoC7D5xuiPKXW/gtXkEdunUj9xzL7OG3PC2jFUIj6vlZtx8OpTnprFSiVBOWNRmPWr/i4dOvlVbxTj7xx1OW5ttSd9G4laIzOINRYbc761OZv6RxgmEVoWR0jA2i4dXJJTau5dtyj5Xdo3y3TBZKFBQIlqgtEq+FajLjQzgLwawiT7XsCLLKyC5bYgUnf1139tcyUr/gypNvgHVY4maPOIOgKyiD/pEXhME5bl3URms628+vI1RiRdKdplbmsK+BqJMyc8gO5KhGRRmsLSsfFEJfht31+VVRzc1QYkfFSU0HV+jWaB9alP9c/kqV3w/sfCr1hE4vtZGUVrUyE0SoqhhKHtKDuDWYZynGZt7NHsoL8HSvyFifnV1aLyND+x5nBH62beHxqxDbRpU0uJQ7gv2imQ5CL3Z0=
  bucket: dawidvdh.com
  acl: public_read
  skip_cleanup: true
  local_dir: build
  region: us-east-1
branches:
  only:
  - master
