language: node_js
node_js:
- node
script:
- mkdir -p build
- cp index.html build/
- ls build
deploy:
  provider: s3
  access_key_id: AKIAJE6HJVEHK2476P4A
  secret_access_key:
    secure: i0bOwCiIRawYk0+4uBA7Kj9r0wUuMaI7QaMQbUKCi1Z1Q+Fuu8c6tKosbwDV0gXz8OsiYBdryTHAu/O0B/tSd8tvHlvqRZPeljtcOZhOqO4X1ESg8cZZXrMg7aPj/zMsjXsZIXkTxIvlKcEFb8oXdkpr55njcwTd2E2ZwS9f6SKbokefsl7Dcg6RC6ztUrh4dwxl4KqLcF3PK70sFS2VVZkEHntj9KcHxrqutbTPtvROJgyl7HoRPGPh0qC7SjKfSmOVB1M2dgpDwYRrqn82JUjzGN84nJskjyXCH0HhsYYkZ4p+m6CQJBP9bkVL4mHbTKm6rKp48KXbuF2DACQMRgJjKYuyLRPuOYuKvATXjhG+28ObcegP7rET5smF+uwpoHlYCKxNx0V96IMfn8kThpyTjw7Zt1I8hWFSMWyuNTmnMnmTsFQ6NMd5Pb9fssMoi7pZEXr/NGltNpySfmpdnm1kTHt68vY7seUfKLsnZt0Ev0MA0ZfXWSep3KBLZyvtormgKkhkAOrts/b+1OPweMKFfq4SmDSWQ5CTcksl/3JjWaFqH85K1v2illcFPa6WtmnFShzauZ2LwUYuackN+KcU7/DMpxEmgDPQE+41DM/tFYqKbNyy+8VgLOCc9VdGzoNB41gimPfQ127YrJcUacFYZ7FCNZ4BLA3c7+VEY24=
  bucket: dawidvdh.com
  acl: public_read
  skip_cleanup: true
  local_dir: build
branches:
  only:
  - master
